function [ ...
    red,        opacityRed,         ...
    lightRed,   opacityLightRed,    ...
    green,      opacityGreen,       ...
    yellow,     opacityYellow,      ...
    orange,     opacityOrange,      ...
    black,      opacityBlack,       ...
    blue,       opacityBlue,        ...
    lightBlue,  opacityLightBlue,   ...
    white,      opacityWhite]       ...
    = colorsAndOpacititesTIR()
% function [red, lightRed, green, yellow, orange, black, blue, lightBlue, ...
%     opacityRed, opacityLightRed, opacityGreen, opacityYellow, opacityOrange, opacityBlack, opacityBlue, opacityLightBlue] ...

% Colors
red         = [1,     0.1,    0.1   ];
lightRed    = [1,     0.1,    0.1   ];
green       = [0.1,   1,      0.1   ];
yellow      = [1,     1,      0     ];
orange      = [1,     0.6471, 0     ];
black       = [0,     0,      0     ];
blue        = [0,     0.4470, 0.7410];
lightBlue   = [0.3010 0.7450  0.9330];
white       = [1,     1,      1     ];

% Opacities
% Set face alpha of each zone
opacityRed       = 0.2;
opacityLightRed  = 0.1;
opacityGreen     = 0.2;
opacityYellow    = 0.2;
opacityOrange    = 0.2;
opacityBlack     = 0.45;
opacityBlue      = 0.3;
opacityLightBlue = 0.45;
opacityWhite     = 0.3;